name: ${DOCKER_PROD_NAME}

services:
  nuxt:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ../../dist:/dist
    command: sh -c "cp -r /app/dist/* /dist/"
